# Generated by Django 4.1.7 on 2023-02-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_proyecto_inversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='inversion',
            field=models.CharField(max_length=200),
        ),
    ]
