# Generated by Django 4.1.7 on 2023-02-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.JSONField()),
                ('gbfs_href', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=200)),
                ('ids', models.CharField(max_length=200)),
                ('location', models.JSONField()),
                ('name', models.CharField(max_length=200)),
                ('stations', models.JSONField()),
            ],
        ),
    ]
